# login
login = '//div[1]/div[2]/div/div/div[2]/app-login-module/app-login/app-login-form/div[2]/div[1]/ui-input[1]/div/div/input'
password = '//div[1]/div[2]/div/div/div[2]/app-login-module/app-login/app-login-form/div[2]/div[1]/ui-input[2]/div/div/input'
log_button = '/html/body/app-root/ng-component/div[1]/div[2]/div/div/div[2]/app-login-module/app-login/app-login-form/div[2]/div[2]/div/div[2]/ui-button/button/div'
accept = '/html/body/app-root/ng-component/div[1]/div[2]/div/div/div[2]/app-login-module/app-sms/div/div[2]/div[1]/app-sms-input/form/div[1]/input'
doc_button = '/html/body/app-root/layout-corporate/div/div/corporate-summary/corporate-summary-info-carousel/div/div/div/ui-corporate-carusel/div[1]/div[2]/div/div/div[4]'
create_doc_button = '/html/body/app-root/layout-corporate/div/div/ng-component/div/div/div[1]/div[2]/ui-button/button'
inn = '/html/body/app-root/layout-corporate/div/div/corporate-document-page/main/div/form/corporate-document-main-form/corporate-document-section[1]/section/div[2]/corporate-document-counterparty-form/div[1]/ui-input/div/div[2]/input'
inn_click = '/html/body/app-root/layout-corporate/div/div/corporate-document-page/main/div/form/corporate-document-main-form/corporate-document-section[1]/section/div[2]/corporate-document-counterparty-form/div[2]/div/div[1]/div/ui-input/div/div[2]/ui-autocomplete-list/div/ui-scrollbar/perfect-scrollbar/div/div[1]/div/div/div[2]'
service = '/html/body/app-root/layout-corporate/div/div/corporate-document-page/main/div/form/corporate-document-main-form/corporate-document-section[3]/section/div[2]/corporate-document-product-service-form/corporate-document-product-service-form-item/div[1]/ui-input-autocomplete/div[2]/div/input'
quantity = '/html/body/app-root/layout-corporate/div/div/corporate-document-page/main/div/form/corporate-document-main-form/corporate-document-section[3]/section/div[2]/corporate-document-product-service-form/corporate-document-product-service-form-item/div[2]/div[1]/div/ui-input/div/div[2]/input'
price = '/html/body/app-root/layout-corporate/div/div/corporate-document-page/main/div/form/corporate-document-main-form/corporate-document-section[3]/section/div[2]/corporate-document-product-service-form/corporate-document-product-service-form-item/div[3]/div[1]/div/ui-input/div/div[2]/input'
cr_button = '/html/body/app-root/layout-corporate/div/div/corporate-document-page/main/div/form/div/div/div[2]/ui-button[2]/button'
reject_button = '//*[@id="dialog-modal-cancel-button"]/button/div'
save_button = '//*[@id="dialog-modal-confirm-button"]/button/div'
close_button = '/html/body/corporate-modal-dialog/ui-modal-window/div[1]/div[1]/ui-icon'
close_invoice_button = '//*[@id="close"]'
comment = '/html/body/app-root/layout-corporate/div/div/corporate-document-page/main/div/form/corporate-document-main-form/corporate-document-section[6]/section/div[2]/div/div/ui-input/div/div[2]/input'