# страница входа
login = '//ui-input[1]/div/div/input'
password = '//ui-input[2]/div/div/input'
log_button = '//ui-button/button/div'
accept = '//app-sms-input/form/div[1]/input'

# страница создания счета на оплату
inn = '//corporate-document-counterparty-form/div[1]/ui-input/div/div[2]/input'
inn_click = '//perfect-scrollbar/div/div[1]/div/div/div[2]'
addres = '//corporate-document-counterparty-form/div[3]/ui-input/div/div[2]/input'
service = '//corporate-document-product-service-form-item/div[1]/ui-input-autocomplete/div[2]/div/input'
quantity = '//corporate-document-product-service-form-item/div[2]/div[1]/div/ui-input/div/div[2]/input'
price = '//corporate-document-product-service-form-item/div[3]/div[1]/div/ui-input/div/div[2]/input'
cr_button = '//ui-button[2]/button'
cancel_button = '//*[@id="dialog-modal-cancel-button"]/button/div'
save_button = '//*[@id="dialog-modal-confirm-button"]/button/div'
close_button = '/html/body/corporate-modal-dialog/ui-modal-window/div[1]/div[1]/ui-icon/span'
close_invoice_button = '//*[@id="close"]'
comment = '//corporate-document-section[6]/section/div[2]/div/div/ui-input/div/div[2]/input'
inn_in_list = '//perfect-scrollbar/div/div[1]/div/div[2]/div[2]/div[2]'
counterparty_button = '//perfect-scrollbar/div/div[1]/ul/li[5]/span'
headder = '//h1'
bot = '//app-root/layout-corporate/div/widget-sidebar/div/div[2]/div[2]'
